[workspace]
members = [
    "apps/dinput8-proxy",
    "apps/rdb-tool",
    "crates/oppw4-hooks",
    "crates/oppw4-lua-support",
    "crates/oppw4-plugin-api",
    "crates/oppw4-rdb",
    "crates/plugins_supports",
    "official_plugins/skin_patcher",
    "official_plugins/weapon_aura",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
oppw4-rdb = { path = "crates/oppw4-rdb" }
oppw4-plugin-api = { path = "crates/oppw4-plugin-api" }
oppw4-hooks = { path = "crates/oppw4-hooks" }
oppw4-lua-support = { path = "crates/oppw4-lua-support" }
plugins_supports = { path = "crates/plugins_supports" }
mlua = { version = "0.10", features = ["lua54", "vendored"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
toml = "0.8"
zip = { version = "2", default-features = false, features = ["deflate"] }
