[workspace]
members = [
    "apps/dinput8-proxy",
    "apps/rdb-tool",
    "crates/struct-api",
    "crates/asm",
    "crates/hooks",
    "crates/lua-api",
    "crates/plugin-api",
    "crates/rdb",
    "crates/plugin-host",
    "official_plugins/skin_patcher",
    "official_plugins/fx_director",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
rdb = { path = "crates/rdb" }
struct-api = { path = "crates/struct-api" }
asm = { path = "crates/asm" }
plugin-api = { path = "crates/plugin-api" }
hooks = { path = "crates/hooks" }
lua-api = { path = "crates/lua-api" }
plugin-host = { path = "crates/plugin-host" }
mlua = { version = "0.10", features = ["lua54", "vendored"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
toml = "0.8"
zip = { version = "2", default-features = false, features = ["deflate"] }
